"use strict";
const productions = [
    {name: 'Produccion', produccion: '<Programa>',                     produce: ['<Sentencia>', 'PUNTOYCOMA', '<ProgramaFin>']},
    {name: 'Produccion', produccion: '<ProgramaFin>',                  produce: ['<Sentencia>', 'PUNTOYCOMA', '<Programa>']},
    {name: 'Produccion', produccion: '<ProgramaFin>',                  produce: ['EPSILON']},
    {name: 'Produccion', produccion: '<Programa>',                     produce: ['EPSILON']},
    {name: 'Produccion', produccion: '<Sentencia>',                    produce: ['<Asignacion>']},
    {name: 'Produccion', produccion: '<Sentencia>',                    produce: ['<Ciclo>']},
    {name: 'Produccion', produccion: '<Sentencia>',                    produce: ['<Condicional>']},
    {name: 'Produccion', produccion: '<Sentencia>',                    produce: ['<Escritura>']},
    {name: 'Produccion', produccion: '<Sentencia>',                    produce: ['<Lectura>']},
    {name: 'Produccion', produccion: '<Sentencia>',                    produce: ['<Definicion>']},
    {name: 'Produccion', produccion: '<Sentencia>',                    produce: ['<Funcion>']},
    {name: 'Produccion', produccion: '<Sentencia>',                    produce: ['<Expresion>']},
    {name: 'Produccion', produccion: '<Definicion>',                   produce: ['VAR', 'ID']},
    {name: 'Produccion', produccion: '<Definicion>',                   produce: ['CONST', 'ID']},
    {name: 'Produccion', produccion: '<Definicion>',                   produce: ['LET', 'ID']},
    {name: 'Produccion', produccion: '<Asignacion>',                   produce: ['ID', 'OPERADORASIGNACION', 'ID']},
    {name: 'Produccion', produccion: '<Asignacion>',                   produce: ['<Definicion>', 'OPERADORASIGNACION', 'ID']},
    {name: 'Produccion', produccion: '<Asignacion>',                   produce: ['<Definicion>', 'OPERADORASIGNACION', 'COMILLA','TEXTO','COMILLA']},
    {name: 'Produccion', produccion: '<Asignacion>',                   produce: ['<Definicion>', 'OPERADORASIGNACION', '<ExpresionLogica>']},
    {name: 'Produccion', produccion: '<Asignacion>',                   produce: ['ID', 'OPERADORASIGNACION', '<Expresion>']},
    {name: 'Produccion', produccion: '<Asignacion>',                   produce: ['<Definicion>', 'OPERADORASIGNACION', '<Expresion>']},
    {name: 'Produccion', produccion: '<Expresion>',                    produce: ['<LlamarFuncion>']},
    {name: 'Produccion', produccion: '<Expresion>',                    produce: ['<ExpresionAritmetica>']},
    {name: 'Produccion', produccion: '<Expresion>',                    produce: ['<ExpresionLista>']},
    {name: 'Produccion', produccion: '<Expresion>',                    produce: ['<ExpresionLogica>']},
    {name: 'Produccion', produccion: '<Funcion>',                      produce: ['FUNCTION','ID','PARENTESIS_OPEN','PARENTESIS_CLOSE','LLAVE_OPEN', '<Programa>', 'LLAVE_CLOSE']},
    {name: 'Produccion', produccion: '<Funcion>',                      produce: ['PARENTESIS_OPEN','PARENTESIS_CLOSE','OPERADORASIGNACION','SIGNO','LLAVE_OPEN', '<Programa>', 'LLAVE_CLOSE']},
    {name: 'Produccion', produccion: '<LlamarFuncion>',                produce: ['ID','PARENTESIS_OPEN','PARENTESIS_CLOSE']},
    {name: 'Produccion', produccion: '<ExpresionAritmetica>',          produce: ['FLOAT', '<ExpresionAritmeticaFinal>']},
    {name: 'Produccion', produccion: '<ExpresionAritmetica>',          produce: ['NUMERO', '<ExpresionAritmeticaFinal>']},
    {name: 'Produccion', produccion: '<ExpresionAritmetica>',          produce: ['ID', '<ExpresionAritmeticaFinal>']},
    {name: 'Produccion', produccion: '<ExpresionAritmetica>',          produce: ['FIRST', 'PARENTESIS_OPEN', '<ListaInterna>', 'PARENTESIS_CLOSE', '<ExpresionAritmeticaFinal>']},
    {name: 'Produccion', produccion: '<ExpresionAritmetica>',          produce: ['PARENTESIS_OPEN','<ExpresionAritmetica>', 'PARENTESIS_CLOSE', '<ExpresionAritmeticaFinal>']},
    {name: 'Produccion', produccion: '<ExpresionAritmeticaFinal>',     produce: ['SUMA', 'SUMA']},
    {name: 'Produccion', produccion: '<ExpresionAritmeticaFinal>',     produce: ['SUMA', 'ID']},
    {name: 'Produccion', produccion: '<ExpresionAritmeticaFinal>',     produce: ['SUMA', '<ExpresionAritmetica>']},
    {name: 'Produccion', produccion: '<ExpresionAritmeticaFinal>',     produce: ['SUMA', 'OPERADORASIGNACION', '<ExpresionAritmetica>']},
    {name: 'Produccion', produccion: '<ExpresionAritmeticaFinal>',     produce: ['RESTA', 'RESTA']},
    {name: 'Produccion', produccion: '<ExpresionAritmeticaFinal>',     produce: ['RESTA', 'ID']},
    {name: 'Produccion', produccion: '<ExpresionAritmeticaFinal>',     produce: ['RESTA', '<ExpresionAritmetica>']},
    {name: 'Produccion', produccion: '<ExpresionAritmeticaFinal>',     produce: ['RESTA', 'OPERADORASIGNACION','<ExpresionAritmetica>']},
    {name: 'Produccion', produccion: '<ExpresionAritmeticaFinal>',     produce: ['PRODUCTO', 'ID']},
    {name: 'Produccion', produccion: '<ExpresionAritmeticaFinal>',     produce: ['PRODUCTO', '<ExpresionAritmetica>']},
    {name: 'Produccion', produccion: '<ExpresionAritmeticaFinal>',     produce: ['DIVISION', 'ID']},
    {name: 'Produccion', produccion: '<ExpresionAritmeticaFinal>',     produce: ['DIVISION', '<ExpresionAritmetica>']},
    {name: 'Produccion', produccion: '<ExpresionAritmeticaFinal>',     produce: ['EPSILON']},
    {name: 'Produccion', produccion: '<ExpresionLista>',               produce: ['<Lista>']},
    {name: 'Produccion', produccion: '<ExpresionLista>',               produce: ['REST', 'PARENTESIS_OPEN', '<ExpresionLista>', 'PARENTESIS_CLOSE']},
    {name: 'Produccion', produccion: '<ExpresionLista>',               produce: ['CONS', 'PARENTESIS_OPEN', '<ExpresionCons>', 'PARENTESIS_CLOSE']},
    {name: 'Produccion', produccion: '<ExpresionCons>',                produce: ['NUMERO', 'COMA', '<ExpresionLista>']},
    {name: 'Produccion', produccion: '<ExpresionCons>',                produce: ['ID', 'COMA', '<ExpresionLista>']},
    {name: 'Produccion', produccion: '<Lista>',                        produce: ['CORCHETE_OPEN', '<ListaInterna>', 'CORCHETE_CLOSE']},
    {name: 'Produccion', produccion: '<ListaInterna>',                 produce: ['NUMERO', '<ListaInternaNumero>']},
    {name: 'Produccion', produccion: '<ListaInterna>',                 produce: ['ID', '<ListaInternaNumero>']},
    {name: 'Produccion', produccion: '<ListaInternaNumero>',           produce: ['COMA', '<ListaInterna>']},
    {name: 'Produccion', produccion: '<ListaInternaNumero>',           produce: ['EPSILON']},
    {name: 'Produccion', produccion: '<ListaInternaNumero>',           produce: ['NUMERO']},
    {name: 'Produccion', produccion: '<ListaInternaNumero>',           produce: ['ID']},
    {name: 'Produccion', produccion: '<Ciclo>',                        produce: ['WHILE','PARENTESIS_OPEN', '<ExpresionLogica>','PARENTESIS_CLOSE' ,'LLAVE_OPEN', '<Programa>', 'LLAVE_CLOSE']},
    {name: 'Produccion', produccion: '<Ciclo>',                        produce: ['WHILE','PARENTESIS_OPEN', '<ExpresionLogicaCompuesta>','PARENTESIS_CLOSE' ,'LLAVE_OPEN', '<Programa>', 'LLAVE_CLOSE']},
    {name: 'Produccion', produccion: '<Ciclo>',                        produce: ['DO','LLAVE_OPEN', '<Programa>', 'LLAVE_CLOSE','WHILE','PARENTESIS_OPEN', '<ExpresionLogica>','PARENTESIS_CLOSE' ]},
    {name: 'Produccion', produccion: '<Ciclo>',                        produce: ['DO','LLAVE_OPEN', '<Programa>', 'LLAVE_CLOSE','WHILE','PARENTESIS_OPEN', '<ExpresionLogicaCompuesta>','PARENTESIS_CLOSE' ]},
    {name: 'Produccion', produccion: '<Ciclo>',                        produce: ['FOR','PARENTESIS_OPEN', '<Asignacion>','PUNTOYCOMA' , '<ExpresionLogica>','PUNTOYCOMA','<Expresion>','PARENTESIS_CLOSE' ,'LLAVE_OPEN', '<Programa>', 'LLAVE_CLOSE']},
    {name: 'Produccion', produccion: '<ExpresionLogica>',              produce: ['ID', '<ExpresionLogicaFinal>']},
    {name: 'Produccion', produccion: '<ExpresionLogica>',              produce: ['TRUE', '<ExpresionLogicaFinal>']},
    {name: 'Produccion', produccion: '<ExpresionLogica>',              produce: ['FALSE', '<ExpresionLogicaFinal>']},
    {name: 'Produccion', produccion: '<ExpresionLogica>',              produce: ['<ExpresionAritmetica>','MAYOR_QUE','<ExpresionAritmetica>']},
    {name: 'Produccion', produccion: '<ExpresionLogica>',              produce: ['<ExpresionAritmetica>','MAYOR_QUE','<ExpresionLogica>']},
    {name: 'Produccion', produccion: '<ExpresionLogica>',              produce: ['<ExpresionAritmetica>','MENOR_QUE','<ExpresionAritmetica>']},
    {name: 'Produccion', produccion: '<ExpresionLogica>',              produce: ['<ExpresionAritmetica>','MENOR_QUE','<ExpresionLogica>']},
    {name: 'Produccion', produccion: '<ExpresionLogica>',              produce: ['<ExpresionAritmetica>','IGUALDAD','<ExpresionAritmetica>']},
    {name: 'Produccion', produccion: '<ExpresionLogica>',              produce: ['<ExpresionAritmetica>','IGUALDAD','<ExpresionLogica>']},
    {name: 'Produccion', produccion: '<ExpresionLogica>',              produce: ['<ExpresionAritmetica>','IGUALDAD_ESTRICTA','<ExpresionAritmetica>']},
    {name: 'Produccion', produccion: '<ExpresionLogica>',              produce: ['<ExpresionAritmetica>','IGUALDAD_ESTRICTA','<ExpresionLogica>']},
    {name: 'Produccion', produccion: '<ExpresionLogica>',              produce: ['<ExpresionAritmetica>','DISTINTO_ESTRICTO','<ExpresionAritmetica>']},
    {name: 'Produccion', produccion: '<ExpresionLogica>',              produce: ['<ExpresionAritmetica>','DISTINTO_ESTRICTO','<ExpresionLogica>']},
    {name: 'Produccion', produccion: '<ExpresionLogica>',              produce: ['<ExpresionAritmetica>','DISTINTO_DE','<ExpresionAritmetica>']},
    {name: 'Produccion', produccion: '<ExpresionLogica>',              produce: ['<ExpresionAritmetica>','DISTINTO_DE','<ExpresionLogica>']},
    {name: 'Produccion', produccion: '<ExpresionLogicaCompuesta>',     produce: ['<ExpresionLogica>','AND','<ExpresionLogica>']},
    {name: 'Produccion', produccion: '<ExpresionLogicaCompuesta>',     produce: ['<ExpresionLogica>','OR','<ExpresionLogica>']},
    //{name: 'Produccion', produccion: '<ExpresionLogicaCompuesta>',     produce: ['<ExpresionLogica>','AND','ExpresionLogicaFinal']},
    //{name: 'Produccion', produccion: '<ExpresionLogicaCompuesta>',     produce: ['<ExpresionAritmetica>','AND','<ExpresionLogica>']},
    {name: 'Produccion', produccion: '<ExpresionLogicaFinal>',         produce: ['MAYOR_QUE', '<ExpresionLogica>']},
    {name: 'Produccion', produccion: '<ExpresionLogicaFinal>',         produce: ['MAYOR_QUE', '<ExpresionAritmetica>']},
    {name: 'Produccion', produccion: '<ExpresionLogicaFinal>',         produce: ['MENOR_QUE', '<ExpresionLogica>']},
    {name: 'Produccion', produccion: '<ExpresionLogicaFinal>',         produce: ['MENOR_QUE', '<ExpresionAritmetica>']},
    {name: 'Produccion', produccion: '<ExpresionLogicaFinal>',         produce: ['IGUALDAD', '<ExpresionLogica>']},
    {name: 'Produccion', produccion: '<ExpresionLogicaFinal>',         produce: ['IGUALDAD', '<ExpresionAritmetica>']},
    {name: 'Produccion', produccion: '<ExpresionLogicaFinal>',         produce: ['IGUALDAD_ESTRICTA', '<ExpresionLogica>']},
    {name: 'Produccion', produccion: '<ExpresionLogicaFinal>',         produce: ['IGUALDAD_ESTRICTA', '<ExpresionAritmetica>']},
    {name: 'Produccion', produccion: '<ExpresionLogicaFinal>',         produce: ['DISTINTO_ESTRICTO', '<ExpresionLogica>']},
    {name: 'Produccion', produccion: '<ExpresionLogicaFinal>',         produce: ['DISTINTO_ESTRICTO', '<ExpresionAritmetica>']},
    {name: 'Produccion', produccion: '<ExpresionLogicaFinal>',         produce: ['DISTINTO_DE', '<ExpresionLogica>']},
    {name: 'Produccion', produccion: '<ExpresionLogicaFinal>',         produce: ['DISTINTO_DE', '<ExpresionAritmetica>']},
    {name: 'Produccion', produccion: '<ExpresionLogicaFinal>',         produce: ['EPSILON']},
    {name: 'Produccion', produccion: '<Condicional>',                  produce: ['IF','PARENTESIS_OPEN', '<ExpresionLogica>','PARENTESIS_CLOSE' ,'LLAVE_OPEN', '<Programa>', '<CierreCondicion>']},
    //{name: 'Produccion', produccion: '<Condicional>',                  produce: ['IF','PARENTESIS_OPEN', '<ExpresionLogica>','PARENTESIS_CLOSE' ,'LLAVE_OPEN', '<Programa>', 'LLAVE_CLOSE']},
    {name: 'Produccion', produccion: '<CierreCondicion>',              produce: ['LLAVE_CLOSE', 'ELSE' ,'LLAVE_OPEN', '<Programa>', 'LLAVE_CLOSE']},
    {name: 'Produccion', produccion: '<CierreCondicion>',              produce: ['LLAVE_CLOSE']},
    {name: 'Produccion', produccion: '<Escritura>',                    produce: ['<EscribirNumero>']},
    {name: 'Produccion', produccion: '<Escritura>',                    produce: ['<EscribirLista>']},
    {name: 'Produccion', produccion: '<Lectura>',                      produce: ['<LecturaNumero>']},
    {name: 'Produccion', produccion: '<Lectura>',                      produce: ['<LecturaLista>']},
    {name: 'Produccion', produccion: '<EscribirNumero>',               produce: ['WRITEINT', '<EscrituraLectura>']},
    {name: 'Produccion', produccion: '<EscribirLista>',                produce: ['WRITELIST', '<EscrituraLectura>']},
    {name: 'Produccion', produccion: '<LecturaNumero>',                produce: ['READINT', '<EscrituraLectura>']},
    {name: 'Produccion', produccion: '<LecturaLista>',                 produce: ['READLIST', '<EscrituraLectura>']},
    {name: 'Produccion', produccion: '<EscrituraLectura>',             produce: ['PARENTESIS_OPEN', '<Cadena>', 'COMA', 'ID', 'PARENTESIS_CLOSE']},
    {name: 'Produccion', produccion: '<EscrituraLectura>',             produce: ['PARENTESIS_OPEN', 'ID', 'PARENTESIS_CLOSE']},
    {name: 'Produccion', produccion: '<Cadena>',                       produce: ['COMILLA', 'TEXTO', 'COMILLA']},
];

module.exports = productions;